import { CommonModule } from '@angular/common';
import { Component, HostListener, OnDestroy } from '@angular/core';

interface Project {
  number: string; title: string; eyebrow: string; summary: string; stack: string[]; services: string[];
  challenge: string; approach: string; outcome: string; accent: string; live?: string; liveLabel?: string; repo?: string; image?: string;
  gallery?: { src: string; label: string; alt: string }[]; confidential?: boolean; role?: string; ownership?: string;
}

interface SkillGroup { label: string; items: string[]; }

@Component({ selector: 'app-root', standalone: true, imports: [CommonModule], templateUrl: './app.component.html', styleUrl: './app.component.css' })
export class AppComponent implements OnDestroy {
  menuOpen = false; scrolled = false; activeProject: Project | null = null;
  readonly projects: Project[] = [
    { number:'01', title:'PracticeFit / Practice Performance', eyebrow:'Enterprise healthcare SaaS', accent:'#668158', repo:'https://github.com/ikramulhaqkhan/practice-performance', image:'/practicefit-performance.png', gallery:[{src:'/practicefit-performance.png',label:'RCM team performance dashboard',alt:'PracticeFit Claim Plus dashboard showing team KPIs, performance trend and user productivity'}], summary:'Revenue-cycle performance shaped into a responsive Angular workspace with team KPIs, benchmark trends, user productivity and claim-quality signals.', stack:['Angular 14','TypeScript','RxJS','PrimeNG','Chart.js'], services:['RCM performance','User productivity','Benchmark trends','Claim quality'], challenge:'Healthcare workflows carry dense claim data, team targets, quality checks and operational alerts. Supervisors still need to understand performance and risk at a glance.', approach:'I created reusable Angular patterns for team KPIs, trend charts, responsive data tables, scrub-pass indicators and actionable productivity states.', outcome:'A publicly verifiable Angular healthcare interface, alongside performance work that reduced load times in complex modules by 30%.' },
    { number:'02', title:'MyConverterApp', eyebrow:'Live digital product', role:'Full-Stack Developer', ownership:'I independently built the frontend and backend, including the responsive product experience, Node.js services, REST APIs, file-processing workflows, SEO structure, Nginx configuration and production deployment.', accent:'#758b66', live:'https://myconverterapp.com', image:'/myconverterapp-home.png', gallery:[{src:'/myconverterapp-home.png',label:'Product homepage & tool discovery',alt:'MyConverterApp homepage with converter search and popular PDF tools'}], summary:'A public conversion platform with 95+ tools that I built end to end, from the responsive frontend and Node.js backend to file processing, SEO and deployment.', stack:['Node.js','REST APIs','JavaScript','Python','Nginx','SEO','Responsive UI'], services:['Full-stack ownership','95+ conversion tools','PDF & image processing','Production deployment'], challenge:'Multi-tool utility products become confusing quickly. Every journey needed to be direct and discoverable while the backend safely handled different file types and conversion jobs.', approach:'I designed the tool-first interface, implemented responsive upload and conversion flows, built the backend services and APIs, structured search-friendly content and configured production deployment.', outcome:'A live public product demonstrating complete ownership across product decisions, frontend engineering, backend development and launch.' },
    { number:'03', title:'IMS — Inventory Management System', eyebrow:'Live inventory & billing platform', role:'Full-Stack Developer', ownership:'I built the Angular frontend and implemented the Node.js backend/API integration. I used AI as a development assistant for selected backend implementation, debugging and refinement while reviewing and integrating the final code myself.', accent:'#ffb86b', image:'/ims-dashboard.png', live:'https://ims.myconverterapp.com/', liveLabel:'Open live demo', gallery:[{src:'/ims-dashboard.png',label:'Dashboard overview',alt:'IMS dashboard with store performance, inventory metrics and recent sales'},{src:'/ims-products.png',label:'Product management',alt:'IMS products screen with categories, search and inventory navigation'},{src:'/ims-billing.png',label:'Billing & point of sale',alt:'IMS billing screen with products, cart and payment controls'}], summary:'A full-stack inventory, billing and shop-management platform covering stock, sales, customers, suppliers, expenses and point-of-sale operations.', stack:['Angular','TypeScript','Node.js','REST APIs','Responsive UI','Billing workflows'], services:['Full-stack implementation','Inventory workflows','Billing & POS','Operational dashboards'], challenge:'Inventory systems can become a wall of tables, cards and controls. High information density and connected backend operations had to remain useful without feeling noisy.', approach:'I built responsive Angular modules, billing flows, dashboard components and supporting APIs. AI assisted selected backend and debugging tasks; I handled integration, validation and final implementation decisions.', outcome:'A publicly testable full-stack product covering dashboard analytics, inventory management, billing and point-of-sale workflows.' },
    { number:'04', title:'IRS — School Management System', eyebrow:'Attendance & school operations', role:'Full-Stack Developer', ownership:'I built the Angular interface and integrated backend/API workflows for attendance, students, staff, fees, payroll and school operations. AI assisted selected backend tasks and debugging, with the implementation reviewed, adapted and integrated by me.', accent:'#6658b8', image:'/irs-school-dashboard.png', gallery:[{src:'/irs-school-dashboard.png',label:'School operations dashboard',alt:'IRS school management dashboard with staff and student attendance, fee summary and quick actions'}], summary:'A full-stack school management system bringing attendance, students, staff, classes, fees, payroll, leaves and daily administration into one workspace.', stack:['Angular','TypeScript','Node.js','REST APIs','Responsive UI','Dashboard UX'], services:['Full-stack implementation','Attendance workflows','Fee & payroll management','School administration'], challenge:'School teams need a fast overview of people, attendance, fees and daily activity, supported by connected backend workflows instead of disconnected records.', approach:'I organized the frontend around priority indicators and common actions, integrated the backend APIs and used AI assistance for selected backend implementation and debugging tasks.', outcome:'A focused full-stack school-management experience connecting attendance, people, finance and daily operations in one actionable workspace.' },
    { number:'05', title:'Medical Billing Operations', eyebrow:'RCM workflow suite', accent:'#b56f78', confidential:true, summary:'Claim Watch, Denial Control, Rejections, Practice Inquiries and assignment-heavy workflows built for fast daily decision-making.', stack:['Angular','PrimeNG','Chart.js','RxJS'], services:['Work queues','Timelines','Assignments','Filters & charts'], challenge:'Billing teams need to identify priority, ownership and status at a glance while moving through large volumes of work.', approach:'I designed scannable states, focused filters, chronological activity and responsive operational layouts, including automated submission flows.', outcome:'Faster-to-read billing screens and automated submission workflows that improved efficiency by 40% by reducing manual intervention.' },
    { number:'06', title:'Tesla Token Launchpad', eyebrow:'React product interface', accent:'#e65b57', image:'/react-token-launchpad.png', gallery:[{src:'/react-token-launchpad.png',label:'Token launchpad project discovery',alt:'React token launchpad interface with KYC steps, wallet connection and open project pools'}], summary:'A responsive React launchpad interface for discovering token pools, completing participation steps and understanding active, upcoming and closed project states.', stack:['React','JavaScript','CSS Grid','Flexbox','Responsive UI'], services:['Token project discovery','KYC journey','Wallet connection','Pool status UI'], challenge:'Launchpad users need to understand participation requirements, project availability, progress and token details without being overwhelmed by financial information.', approach:'I structured the experience around a clear four-step journey, reusable project cards, visible pool progress and consistent status treatment across open, upcoming and closed projects.', outcome:'A structured React interface that makes a dense token-launchpad catalogue easier to scan and navigate across responsive layouts.' },
    { number:'07', title:'Payer & Contract Workflows', eyebrow:'Healthcare product UI', accent:'#6ee7b7', confidential:true, summary:'Multi-step payer registration, contract scope, procedures, pricing and selection flows made easier to understand and configure.', stack:['Angular','TypeScript','Reactive Forms','Responsive UI'], services:['Complex forms','Stateful selection','Pricing UI','Workflow steps'], challenge:'Contract configuration involves dependent choices and detailed data, making errors easy and progress difficult to understand.', approach:'I applied progressive disclosure, visible state, responsive selectors and structured data entry patterns.', outcome:'A clearer, more predictable setup experience for complex payer and contract information.' }
  ];
  readonly capabilities = [
    { no:'01', title:'Understand', text:'I translate complex business rules and healthcare requirements into clear user flows before implementation starts.', meta:'REQUIREMENTS · FLOWS · PRIORITIES' },
    { no:'02', title:'Architect', text:'I build reusable Angular components, reactive forms and RxJS patterns for workflows that need to scale.', meta:'ANGULAR · TYPESCRIPT · RXJS' },
    { no:'03', title:'Build', text:'I connect APIs and shape dense tables, filters, charts and operational states into focused product interfaces.', meta:'PRIMENG · CHART.JS · REST' },
    { no:'04', title:'Refine', text:'I polish responsive behavior, accessibility, validation and edge cases so the experience is ready for real users.', meta:'RESPONSIVE · A11Y · QA' }
  ];
  readonly skillGroups: SkillGroup[] = [
    { label:'Core', items:['Angular','TypeScript','RxJS','JavaScript'] },
    { label:'UI', items:['PrimeNG','Bootstrap','Responsive CSS','HTML','Chart.js'] },
    { label:'Additional', items:['React','Next.js','Node.js','REST APIs','Git','Python'] }
  ];
  ngOnDestroy(): void { document.body.style.overflow=''; }
  @HostListener('window:scroll') onScroll(): void { this.scrolled = window.scrollY > 24; }
  @HostListener('document:keydown.escape') onEscape(): void { this.closeProject(); this.menuOpen=false; }
  toggleMenu(): void { this.menuOpen=!this.menuOpen; } closeMenu(): void { this.menuOpen=false; }
  openProject(project: Project): void { this.activeProject=project; document.body.style.overflow='hidden'; }
  closeProject(): void { this.activeProject=null; document.body.style.overflow=''; }
}
